---
- hosts: dbserver
  tasks:
  - name: execute any basic linux command
    command: hostname -f
    register: cmd_content
  - name: debug statement for os info
    debug:
<<<<<<< HEAD
      msg: "Os family is {{ansible_os_family}} so will skip other operating system specific tasks"      
=======
      msg: "Os family is {{ansible_os_family}} so will skip other operating system specific tasks"
>>>>>>> 999ee9c2d8668a8cb1f0b502309af940df582796
  - name: print command result
    debug: 
      msg: "{{ cmd_content.stdout}}"
    when: cmd_content.stderr == ""       
  - name: print command error if present
    debug: 
      msg: "{{ cmd_content.stderr}}"
    when: cmd_content.stderr != ""
  - debug:
     msg: "System {{ inventory_hostname}} has uuid {{ ansible_product_uuid }}"
